[package]
name = "mineflake"
version = "0.1.0"
edition = "2021"
description = "A CLI that powers Mineflake"
authors = [
  "Egor Ternovoy <cofob@riseup.net>"
]
license = "MIT"

[dependencies]

[profile.release]
overflow-checks = true
incremental = false
opt-level = 3
debug = false
strip = true
lto = true
