[package]
name = "mineflake"
version = "0.1.0"
edition = "2021"
description = "A CLI that powers Mineflake"
authors = [
  "Egor Ternovoy <cofob@riseup.net>"
]
license = "MIT"

[dependencies]
# Argument parsing
clap = "4.0.18"
# Serialization
serde = "1.0.147"
serde_json = "1.0.87"

[profile.release]
overflow-checks = true
incremental = false
opt-level = 3
debug = false
strip = true
lto = true
