name: Cache derivations & Update repo

on:
  push:
    # branches:
    #   - main
    #   - dev

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v12
        with:
          name: nix-community
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build derivations
        run: |
          nix build .

      - name: Print store paths
        run: |
          cat result/buildInputs

      - name: Generate repo.json
        run: |
          nix-shell -p nodejs --run "cd .github/repo_pinner && npm install && node index.mjs ../../result/buildInputs"
          mv .github/repo_pinner/repo.json repo-new.json
          git fetch
          git checkout origin/repo
          git pull origin repo
          rm repo.json
          mv repo-new.json repo.json
        env:
          WEB3STORAGE_TOKEN: ${{ secrets.WEB3STORAGE_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update repo.json"

      - name: Push changes
        # if: github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "refs/heads/repo"
