name: Cache derivations & Update repo

on:
  push:
    # branches:
    #   - main
    #   - dev

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v12
        with:
          name: nix-community
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build derivations
        run: |
          nix build .

      - name: Print store paths
        run: |
          cat result/buildInputs

      - name: Generate repo.json
        ignore_errors: true
        run: |
          nix-shell -p nodejs --run "cd .github/repo_pinner && npm install && node index.mjs ../../result/buildInputs"
          mv .github/repo_pinner/repo.json repo-new.json
          git fetch
          git checkout origin/repo
          git pull
          rm repo.json
          mv repo-new.json repo.json
        env:
          WEB3STORAGE_TOKEN: ${{ secrets.WEB3STORAGE_TOKEN }}

      - name: Push repo.json
        # if: github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: "repo.json"
          default_author: github_actions
          message: "Update repo.json"
