name: Test & lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Lint
        run: |
          nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check ."

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu

      - name: Install mingw
        run: |
          sudo apt-get install -y mingw-w64

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: cli

      - name: Check formatting
        run: |
          cd cli
          cargo fmt --all -- --check

      - name: Generate code coverage
        run: |
          cd cli
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cli/lcov.info
          fail_ci_if_error: true

      - name: Check packages
        run: |
          cd cli
          cargo check

      - name: Test crate
        run: |
          cd cli
          cargo test --all-features
          cargo test --no-default-features --features "cli"
          cargo test --no-default-features --features "cli,net"
          cargo b --target x86_64-pc-windows-gnu
