name: Test & lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Lint
        run: |
          nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check ."

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: cli

      - name: Check formatting
        run: |
          cd cli
          cargo fmt --all -- --check

      - name: Check packages
        run: |
          cd cli
          cargo check

      - name: Test crate
        run: |
          cd cli
          cargo test
          cargo test --all-features
          cargo test --no-default-features --features "cli"
          cargo test --no-default-features --features "cli,net"
          cargo test --target x86_64-pc-windows-gnu
          cargo test --all-features --target x86_64-pc-windows-gnu
          cargo test --no-default-features --features "cli" --target x86_64-pc-windows-gnu
          cargo test --no-default-features --features "cli,net" --target x86_64-pc-windows-gnu
