name: Pin IPFS

on:
  push:
    branches:
      - main
      - dev

jobs:
  pin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Pin IPFS CIDs
        run: |
          nix-shell -p python3 python3Packages.requests --run "python3 .github/pin_all.py"
        env:
          CLUSTER_ADDRESS: ${{ secrets.CLUSTER_PY_ADDRESS }}
          CLUSTER_USERNAME: ${{ secrets.CLUSTER_USERNAME }}
          CLUSTER_SECRET: ${{ secrets.CLUSTER_SECRET }}
