name: Cargo test

on:
  push:
  pull_request:

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: cli

      - name: Check formatting
        run: |
          cd cli
          cargo fmt --all -- --check

      - name: Check packages
        run: |
          cd cli
          cargo check

      - name: Test crate
        run: |
          cd cli
          cargo test
