name: Cargo test

on:
  push:
  pull_request:

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Fmt
        run: |
          cd cli
          cargo fmt --check

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: cli

      - name: Test
        run: |
          cd cli
          cargo test

      - name: Check
        run: |
          cd cli
          cargo check
